logging:
  level:
    com.spring.security : debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: admin
  thymeleaf:
    cache: false # 关闭页面缓存
    encoding: UTF-8 # 模板编码
    prefix: classpath:/templates/  # 页面映射路径
    suffix: .html # 试图后的后缀
  custom:
    login-type: string
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.spring.security.entity
  mapper-locations:
    - classpath:mybatis/mapper/**